name = "marelunebali"
pages_build_output_dir = "./dist"
compatibility_date = "2026-06-25"

# Default vars (development preview)
[vars]
ENVIRONMENT = "development"

# Production environment - Add webhook URL here
[env.production.vars]
MAKE_WEBHOOK_URL = "https://hook.eu1.make.com/c4gqpouxm8w807i14zcwlvoxmqtj9spc"
ENVIRONMENT = "production"
